export const COUNTRIES = {
  FR: {
    code: 'FR',
    name: 'France',
    flag: '\u{1F1EB}\u{1F1F7}',
    center: [2.3522, 46.6034],
    zoom: 6,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'SP95-E10' },
      { id: 'SP98', label: 'SP98' },
      { id: 'Gazole', label: 'Diesel (B7)' },
      { id: 'SP95', label: 'SP95 (E5)' },
      { id: 'E85', label: 'E85' },
      { id: 'GPLc', label: 'GPL' },
    ],
    defaultFuel: 'E10',
    source: 'data.economie.gouv.fr',
    sourceUrl: 'https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/api/',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    flag: '\u{1F1E9}\u{1F1EA}',
    center: [10.4515, 51.1657],
    zoom: 6,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tanker\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  HR: {
    code: 'HR',
    name: 'Croatia',
    flag: '\u{1F1ED}\u{1F1F7}',
    center: [15.978, 45.815],
    zoom: 7,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'eurosuper95', label: 'Eurosuper 95' },
      { id: 'eurosuper100', label: 'Eurosuper 100' },
      { id: 'eurodizel', label: 'Eurodizel' },
      { id: 'lpg', label: 'UNP (LPG)' },
    ],
    defaultFuel: 'eurosuper95',
    source: 'Ministarstvo gospodarstva (mzoe-gor.hr)',
    sourceUrl: 'https://mzoe-gor.hr/',
  },
  LU: {
    code: 'LU',
    name: 'Luxembourg',
    flag: '\u{1F1F1}\u{1F1FA}',
    center: [6.1296, 49.8153],
    zoom: 10,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'Super 95 (E10)' },
      { id: 'SP98', label: 'Super 98' },
      { id: 'diesel', label: 'Diesel (B7)' },
    ],
    defaultFuel: 'E10',
    source: 'Carbu.com',
    sourceUrl: 'https://carbu.com/luxembourg/',
  },
  PT: {
    code: 'PT',
    name: 'Portugal',
    flag: '\u{1F1F5}\u{1F1F9}',
    center: [-8.2245, 39.3999],
    zoom: 7,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina_95', label: 'Gasolina 95' },
      { id: 'gasoleo', label: 'Gas\u00F3leo' },
      { id: 'gasoleo_especial', label: 'Gas\u00F3leo Especial' },
      { id: 'gpl', label: 'GPL Auto' },
    ],
    defaultFuel: 'gasolina_95',
    source: 'DGEG (precoscombustiveis.dgeg.gov.pt)',
    sourceUrl: 'https://precoscombustiveis.dgeg.gov.pt/',
  },
  SI: {
    code: 'SI',
    name: 'Slovenia',
    flag: '\u{1F1F8}\u{1F1EE}',
    center: [14.9955, 46.1512],
    zoom: 9,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: '95', label: 'NMB-95' },
      { id: 'dizel', label: 'Diesel' },
      { id: '98', label: 'NMB-98' },
      { id: 'avtoplin-lpg', label: 'LPG' },
    ],
    defaultFuel: '95',
    source: 'goriva.si',
    sourceUrl: 'https://goriva.si/',
  },
  UK: {
    code: 'UK',
    name: 'United Kingdom',
    flag: '\u{1F1EC}\u{1F1E7}',
    center: [-1.1743, 52.3555],
    zoom: 6,
    currency: 'p',
    decimals: 1,
    unit: 'L',
    fuelTypes: [
      { id: 'unleaded', label: 'Unleaded' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'super_unleaded', label: 'Super Unleaded' },
    ],
    defaultFuel: 'unleaded',
    source: 'CMA Retailer Feeds (via Worker)',
    sourceUrl: 'https://www.gov.uk/guidance/access-fuel-price-data',
  },
  IE: {
    code: 'IE',
    name: 'Ireland',
    flag: '\u{1F1EE}\u{1F1EA}',
    center: [-7.5, 53.4],
    zoom: 7,
    currency: 'c',
    decimals: 1,
    unit: 'L',
    fuelTypes: [
      { id: 'unleaded', label: 'Petrol' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'unleaded',
    source: 'Pumps.ie',
    sourceUrl: 'https://www.pumps.ie/',
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    flag: '\u{1F1EA}\u{1F1F8}',
    center: [-3.7038, 40.4168],
    zoom: 6,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina95', label: 'Gasolina 95' },
      { id: 'gasolina98', label: 'Gasolina 98' },
      { id: 'gasoleo', label: 'Gas\u00F3leo A' },
      { id: 'glp', label: 'GLP' },
    ],
    defaultFuel: 'gasolina95',
    source: 'Ministerio (geoportalgasolineras)',
    sourceUrl: 'https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarworkerantes/PreciosCarworkerantes/help',
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    flag: '\u{1F1EE}\u{1F1F9}',
    center: [12.5674, 41.8719],
    zoom: 6,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'benzina', label: 'Benzina' },
      { id: 'gasolio', label: 'Gasolio' },
      { id: 'gpl', label: 'GPL' },
      { id: 'metano', label: 'Metano' },
    ],
    defaultFuel: 'benzina',
    source: 'MIMIT Open Data (via Worker)',
    sourceUrl: 'https://www.mimit.gov.it/images/exportCSV/',
  },
  AT: {
    code: 'AT',
    name: 'Austria',
    flag: '\u{1F1E6}\u{1F1F9}',
    center: [13.3333, 47.3333],
    zoom: 7,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'SUP', label: 'Super (E5)' },
      { id: 'DIE', label: 'Diesel' },
      { id: 'GAS', label: 'CNG/Erdgas' },
    ],
    defaultFuel: 'SUP',
    source: 'E-Control Spritpreisrechner',
    sourceUrl: 'https://api.e-control.at/sprit/1.0/',
  },
  KR: {
    code: 'KR',
    name: 'South Korea',
    flag: '\u{1F1F0}\u{1F1F7}',
    center: [127.7669, 35.9078],
    zoom: 7,
    currency: '\u20A9',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'B027', label: 'Gasoline' },
      { id: 'B034', label: 'Premium Gasoline' },
      { id: 'D047', label: 'Diesel' },
      { id: 'K015', label: 'LPG' },
    ],
    defaultFuel: 'B027',
    source: 'Opinet (KNOC)',
    sourceUrl: 'https://www.opinet.co.kr/',
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    flag: '\u{1F1E8}\u{1F1F1}',
    center: [-70.6693, -33.4489],
    zoom: 6,
    currency: 'CLP',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina93', label: 'Gasolina 93' },
      { id: 'gasolina95', label: 'Gasolina 95' },
      { id: 'gasolina97', label: 'Gasolina 97' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'glp', label: 'GLP' },
    ],
    defaultFuel: 'gasolina93',
    source: 'CNE (Comisi\u00F3n Nacional de Energ\u00EDa)',
    sourceUrl: 'https://www.cne.cl/',
  },
  AU: {
    code: 'AU',
    name: 'Australia',
    flag: '\u{1F1E6}\u{1F1FA}',
    center: [133.7751, -25.2744],
    zoom: 4,
    currency: 'c',
    decimals: 1,
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'E10' },
      { id: 'ULP', label: 'Unleaded 91' },
      { id: 'PULP95', label: 'Premium 95' },
      { id: 'PULP98', label: 'Premium 98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'LPG', label: 'LPG' },
    ],
    defaultFuel: 'E10',
    source: 'FuelCheck NSW, FuelWatch WA, QLD Open Data',
    sourceUrl: 'https://api.nsw.gov.au/',
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    flag: '\u{1F1F2}\u{1F1FD}',
    center: [-99.1332, 19.4326],
    zoom: 6,
    currency: 'MX$',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'regular', label: 'Regular' },
      { id: 'premium', label: 'Premium' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'regular',
    source: 'CRE (datos.gob.mx)',
    sourceUrl: 'https://datos.gob.mx/',
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    flag: '\u{1F1E7}\u{1F1F7}',
    center: [-47.8825, -15.7942],
    zoom: 5,
    currency: 'R$',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina', label: 'Gasolina Comum' },
      { id: 'gasolina_ad', label: 'Gasolina Aditivada' },
      { id: 'etanol', label: 'Etanol' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'gnv', label: 'GNV' },
    ],
    defaultFuel: 'gasolina',
    source: 'ANP (Ag\u00EAncia Nacional do Petr\u00F3leo)',
    sourceUrl: 'https://www.gov.br/anp/',
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    flag: '\u{1F1E6}\u{1F1F7}',
    center: [-58.3816, -34.6037],
    zoom: 5,
    currency: 'ARS',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'nafta_super', label: 'Nafta S\u00FAper' },
      { id: 'nafta_premium', label: 'Nafta Premium' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'diesel_premium', label: 'Diesel Premium' },
      { id: 'gnc', label: 'GNC' },
    ],
    defaultFuel: 'nafta_super',
    source: 'Secretar\u00EDa de Energ\u00EDa',
    sourceUrl: 'https://datos.gob.ar/dataset/energia-precios-surtidor',
  },
  CH: {
    code: 'CH',
    name: 'Switzerland',
    flag: '\u{1F1E8}\u{1F1ED}',
    center: [8.2275, 46.8182],
    zoom: 7,
    currency: 'CHF',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'E95', label: 'Benzin 95' },
      { id: 'E98', label: 'Benzin 98' },
      { id: 'Diesel', label: 'Diesel' },
    ],
    defaultFuel: 'E95',
    source: 'Comparis.ch (TCS)',
    sourceUrl: 'https://www.comparis.ch/benzin-preise',
  },
  DK: {
    code: 'DK',
    name: 'Denmark',
    flag: '\u{1F1E9}\u{1F1F0}',
    center: [9.5018, 56.2639],
    zoom: 7,
    currency: 'kr',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'e10', label: 'Benzin 95 E10' },
      { id: 'e5', label: 'Benzin 95 E5' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'diesel_extra', label: 'Diesel Extra' },
    ],
    defaultFuel: 'e10',
    source: 'Q8/F24/Shell DK',
    sourceUrl: 'https://www.q8.dk/',
  },
  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    flag: '\u{1F1F3}\u{1F1FF}',
    center: [174.886, -40.9006],
    zoom: 6,
    currency: 'NZ$',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: '91', label: '91 Octane' },
      { id: '95', label: '95 Octane' },
      { id: '98', label: '98 Octane' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: '91',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    flag: '\u{1F1F3}\u{1F1F1}',
    center: [5.2913, 52.1326],
    zoom: 8,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'euro95', label: 'Euro 95' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'euro95',
    source: 'Brandstof-zoeker.nl',
    sourceUrl: 'https://www.brandstof-zoeker.nl/',
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    flag: '\u{1F1E7}\u{1F1EA}',
    center: [4.4699, 50.5039],
    zoom: 8,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'Super 95 (E10)' },
      { id: 'SP98', label: 'Super 98' },
      { id: 'diesel', label: 'Diesel (B7)' },
      { id: 'LPG', label: 'LPG' },
    ],
    defaultFuel: 'E10',
    source: 'Carbu.com',
    sourceUrl: 'https://carbu.com/belgique/',
  },
  GR: {
    code: 'GR',
    name: 'Greece',
    flag: '\u{1F1EC}\u{1F1F7}',
    center: [23.7275, 37.9838],
    zoom: 7,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'unleaded_95', label: 'Unleaded 95' },
      { id: 'unleaded_100', label: 'Unleaded 100' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'unleaded_95',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  },
  MY: {
    code: 'MY',
    name: 'Malaysia',
    flag: '\u{1F1F2}\u{1F1FE}',
    center: [101.6869, 3.139],
    zoom: 7,
    currency: 'RM',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'RON95', label: 'RON 95' },
      { id: 'RON97', label: 'RON 97' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'RON95',
    source: 'data.gov.my',
    sourceUrl: 'https://data.gov.my/',
  },
  AE: {
    code: 'AE',
    name: 'UAE',
    flag: '\u{1F1E6}\u{1F1EA}',
    center: [55.2708, 25.2048],
    zoom: 8,
    currency: 'AED',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'super98', label: 'Super 98' },
      { id: 'special95', label: 'Special 95' },
      { id: 'eplus91', label: 'E-Plus 91' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'special95',
    source: 'Fuel Price Committee',
    sourceUrl: 'https://www.moenr.gov.ae/',
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    flag: '\u{1F1FF}\u{1F1E6}',
    center: [28.0473, -26.2041],
    zoom: 6,
    currency: 'R',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'ULP95', label: '95 Unleaded' },
      { id: 'ULP93', label: '93 Unleaded' },
      { id: 'diesel_50', label: 'Diesel 50ppm' },
      { id: 'diesel_500', label: 'Diesel 500ppm' },
    ],
    defaultFuel: 'ULP95',
    source: 'Dept. of Energy',
    sourceUrl: 'https://www.energy.gov.za/',
  },
  IN: {
    code: 'IN',
    name: 'India',
    flag: '\u{1F1EE}\u{1F1F3}',
    center: [78.9629, 20.5937],
    zoom: 5,
    currency: '\u20B9',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'petrol', label: 'Petrol' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'cng', label: 'CNG' },
    ],
    defaultFuel: 'petrol',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  },
  EE: {
    code: 'EE',
    name: 'Estonia',
    flag: '\u{1F1EA}\u{1F1EA}',
    center: [25.0136, 58.5953],
    zoom: 8,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'e95', label: '95 (E10)' },
      { id: 'e98', label: '98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work (Waze)',
    sourceUrl: 'https://gas.didnt.work/',
  },
  LV: {
    code: 'LV',
    name: 'Latvia',
    flag: '\u{1F1F1}\u{1F1FB}',
    center: [24.1052, 56.9496],
    zoom: 8,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'e95', label: '95' },
      { id: 'e98', label: '98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work (Waze)',
    sourceUrl: 'https://gas.didnt.work/',
  },
  LT: {
    code: 'LT',
    name: 'Lithuania',
    flag: '\u{1F1F1}\u{1F1F9}',
    center: [23.8813, 55.1694],
    zoom: 8,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'e95', label: '95' },
      { id: 'e98', label: '98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work (Waze)',
    sourceUrl: 'https://gas.didnt.work/',
  },
  PL: {
    code: 'PL',
    name: 'Poland',
    flag: '\u{1F1F5}\u{1F1F1}',
    center: [19.1451, 51.9194],
    zoom: 6,
    currency: 'z\u0142',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'pb95', label: 'Pb95' },
      { id: 'pb98', label: 'Pb98' },
      { id: 'diesel', label: 'Diesel (ON)' },
      { id: 'lpg', label: 'LPG' },
      { id: 'on_plus', label: 'ON Plus' },
    ],
    defaultFuel: 'pb95',
    source: 'gas.didnt.work (Waze)',
    sourceUrl: 'https://gas.didnt.work/',
  },
  TH: {
    code: 'TH',
    name: 'Thailand',
    flag: '\u{1F1F9}\u{1F1ED}',
    center: [100.5018, 13.7563],
    zoom: 6,
    currency: '฿',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'gasohol95', label: 'Gasohol 95' },
      { id: 'gasohol91', label: 'Gasohol 91' },
      { id: 'e20', label: 'Gasohol E20' },
      { id: 'diesel_premium', label: 'Hi Premium Diesel' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'gasohol95',
    source: 'PTT / Bangchak',
    sourceUrl: 'https://oil-price.bangchak.co.th/',
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    flag: '\u{1F1EF}\u{1F1F5}',
    center: [139.6917, 35.6895],
    zoom: 6,
    currency: '¥',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'regular', label: 'Regular' },
      { id: 'premium', label: 'Premium' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'regular',
    source: 'gogo.gs',
    sourceUrl: 'https://gogo.gs/',
  },
  ID: {
    code: 'ID',
    name: 'Indonesia',
    flag: '\u{1F1EE}\u{1F1E9}',
    center: [106.8456, -6.2088],
    zoom: 5,
    currency: 'Rp',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'pertalite', label: 'Pertalite (RON 90)' },
      { id: 'pertamax', label: 'Pertamax (RON 92)' },
      { id: 'pertamax_turbo', label: 'Pertamax Turbo (RON 98)' },
      { id: 'solar', label: 'Bio Solar (Diesel)' },
      { id: 'dexlite', label: 'Dexlite (Diesel CN51)' },
    ],
    defaultFuel: 'pertalite',
    source: 'Pertamina / BPH Migas',
    sourceUrl: 'https://www.pertamina.com/',
  },
  FI: {
    code: 'FI',
    name: 'Finland',
    flag: '\u{1F1EB}\u{1F1EE}',
    center: [25.7482, 61.9241],
    zoom: 6,
    currency: '\u20AC',
    decimals: 3,
    unit: 'L',
    fuelTypes: [
      { id: 'e95', label: '95 (E10)' },
      { id: 'e98', label: '98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work (Waze)',
    sourceUrl: 'https://gas.didnt.work/',
  },
  RO: {
    code: 'RO',
    name: 'Romania',
    flag: '\u{1F1F7}\u{1F1F4}',
    center: [25.0, 45.9],
    zoom: 7,
    currency: 'RON',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'benzina95', label: 'Benzin\u0103 95' },
      { id: 'benzina_premium', label: 'Benzin\u0103 Premium' },
      { id: 'diesel', label: 'Motorin\u0103' },
      { id: 'diesel_premium', label: 'Motorin\u0103 Premium' },
      { id: 'gpl', label: 'GPL' },
    ],
    defaultFuel: 'benzina95',
    source: 'PretCarburant.ro',
    sourceUrl: 'https://pretcarburant.ro/',
  },
  HU: {
    code: 'HU',
    name: 'Hungary',
    flag: '\u{1F1ED}\u{1F1FA}',
    center: [19.0402, 47.4979],
    zoom: 7,
    currency: 'Ft',
    decimals: 0,
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Benzin 95' },
      { id: 'diesel', label: 'D\u00EDzel' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'e5',
    source: 'benzinkutarak.hu',
    sourceUrl: 'https://www.benzinkutarak.hu/',
  },
  CZ: {
    code: 'CZ',
    name: 'Czech Republic',
    flag: '\u{1F1E8}\u{1F1FF}',
    center: [15.473, 49.8175],
    zoom: 7,
    currency: 'K\u010D',
    decimals: 1,
    unit: 'L',
    fuelTypes: [
      { id: 'natural95', label: 'Natural 95' },
      { id: 'diesel', label: 'Nafta' },
      { id: 'lpg', label: 'LPG' },
    ],
    defaultFuel: 'natural95',
    source: 'ceskybenzin.cz',
    sourceUrl: 'https://www.ceskybenzin.cz/',
  },
  NO: {
    code: 'NO',
    name: 'Norway',
    flag: '\u{1F1F3}\u{1F1F4}',
    center: [10.7522, 59.9139],
    zoom: 6,
    currency: 'kr',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'gasoline_95', label: 'Bensin 95' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'gasoline_95',
    source: 'Drivstoffappen',
    sourceUrl: 'https://drivstoffappen.no/',
  },
  SE: {
    code: 'SE',
    name: 'Sweden',
    flag: '\u{1F1F8}\u{1F1EA}',
    center: [18.0686, 59.3293],
    zoom: 5,
    currency: 'kr',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: '95', label: 'Bensin 95' },
      { id: '98', label: 'Bensin 98' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'etanol', label: 'E85' },
    ],
    defaultFuel: '95',
    source: 'Bensinpriser.nu',
    sourceUrl: 'https://bensinpriser.nu/',
  },
  TR: {
    code: 'TR',
    name: 'Turkey',
    flag: '\u{1F1F9}\u{1F1F7}',
    center: [32.86, 39.93],
    zoom: 6,
    currency: '₺',
    decimals: 2,
    unit: 'L',
    fuelTypes: [
      { id: 'benzin95', label: 'Benzin 95' },
      { id: 'motorin', label: 'Motorin (Diesel)' },
      { id: 'lpg', label: 'LPG (Otogaz)' },
    ],
    defaultFuel: 'benzin95',
    source: 'OPET + OpenStreetMap',
    sourceUrl: 'https://www.opet.com.tr/akaryakit-fiyatlari',
  },
};

export const DEFAULT_COUNTRY = 'FR';
