export const COUNTRIES = {
  FR: {
    code: 'FR',
    name: 'France',
    flag: '\u{1F1EB}\u{1F1F7}',
    center: [2.3522, 46.6034],
    zoom: 6,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'SP95-E10' },
      { id: 'SP98', label: 'SP98' },
      { id: 'Gazole', label: 'Diesel (B7)' },
      { id: 'SP95', label: 'SP95 (E5)' },
      { id: 'E85', label: 'E85' },
      { id: 'GPLc', label: 'GPL' },
    ],
    defaultFuel: 'E10',
    source: 'data.economie.gouv.fr',
    sourceUrl: 'https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/api/',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    flag: '\u{1F1E9}\u{1F1EA}',
    center: [10.4515, 51.1657],
    zoom: 6,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tankerk\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  HR: {
    code: 'HR',
    name: 'Croatia',
    flag: '\u{1F1ED}\u{1F1F7}',
    center: [15.978, 45.815],
    zoom: 7,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tankerk\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  LU: {
    code: 'LU',
    name: 'Luxembourg',
    flag: '\u{1F1F1}\u{1F1FA}',
    center: [6.1296, 49.8153],
    zoom: 10,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tankerk\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  PT: {
    code: 'PT',
    name: 'Portugal',
    flag: '\u{1F1F5}\u{1F1F9}',
    center: [-8.2245, 39.3999],
    zoom: 7,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tankerk\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  SI: {
    code: 'SI',
    name: 'Slovenia',
    flag: '\u{1F1F8}\u{1F1EE}',
    center: [14.9955, 46.1512],
    zoom: 9,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'e5', label: 'Super E5' },
      { id: 'e10', label: 'Super E10' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'e5',
    source: 'Tankerk\u00F6nig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  },
  UK: {
    code: 'UK',
    name: 'United Kingdom',
    flag: '\u{1F1EC}\u{1F1E7}',
    center: [-1.1743, 52.3555],
    zoom: 6,
    currency: 'p',
    unit: 'L',
    fuelTypes: [
      { id: 'unleaded', label: 'Unleaded' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'super_unleaded', label: 'Super Unleaded' },
    ],
    defaultFuel: 'unleaded',
    source: 'GOV.UK Fuel Finder',
    sourceUrl: 'https://www.gov.uk/guidance/access-fuel-price-data',
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    flag: '\u{1F1EA}\u{1F1F8}',
    center: [-3.7038, 40.4168],
    zoom: 6,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina95', label: 'Gasolina 95' },
      { id: 'gasolina98', label: 'Gasolina 98' },
      { id: 'gasoleo', label: 'Gas\u00F3leo A' },
      { id: 'glp', label: 'GLP' },
    ],
    defaultFuel: 'gasolina95',
    source: 'Ministerio (geoportalgasolineras)',
    sourceUrl: 'https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarworkerantes/PreciosCarworkerantes/help',
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    flag: '\u{1F1EE}\u{1F1F9}',
    center: [12.5674, 41.8719],
    zoom: 6,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'benzina', label: 'Benzina' },
      { id: 'gasolio', label: 'Gasolio' },
      { id: 'gpl', label: 'GPL' },
      { id: 'metano', label: 'Metano' },
    ],
    defaultFuel: 'benzina',
    source: 'MIMIT Open Data',
    sourceUrl: 'https://www.mimit.gov.it/it/open-data/elenco-dataset/carworkeranti-702prezzi-702702702praticati-702e-702702702702anagrafica-702degli-702impianti',
  },
  AT: {
    code: 'AT',
    name: 'Austria',
    flag: '\u{1F1E6}\u{1F1F9}',
    center: [13.3333, 47.3333],
    zoom: 7,
    currency: '\u20AC',
    unit: 'L',
    fuelTypes: [
      { id: 'SUP', label: 'Super (E5)' },
      { id: 'GOE', label: 'Diesel' },
      { id: 'GAS', label: 'CNG/Erdgas' },
    ],
    defaultFuel: 'SUP',
    source: 'E-Control Spritpreisrechner',
    sourceUrl: 'https://api.e-control.at/sprit/1.0/',
  },
  KR: {
    code: 'KR',
    name: 'South Korea',
    flag: '\u{1F1F0}\u{1F1F7}',
    center: [127.7669, 35.9078],
    zoom: 7,
    currency: '\u20A9',
    unit: 'L',
    fuelTypes: [
      { id: 'B027', label: 'Gasoline' },
      { id: 'B034', label: 'Premium Gasoline' },
      { id: 'D047', label: 'Diesel' },
      { id: 'K015', label: 'LPG' },
    ],
    defaultFuel: 'B027',
    source: 'Opinet (KNOC)',
    sourceUrl: 'https://www.opinet.co.kr/',
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    flag: '\u{1F1E8}\u{1F1F1}',
    center: [-70.6693, -33.4489],
    zoom: 6,
    currency: '$',
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina93', label: 'Gasolina 93' },
      { id: 'gasolina95', label: 'Gasolina 95' },
      { id: 'gasolina97', label: 'Gasolina 97' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'glp', label: 'GLP' },
    ],
    defaultFuel: 'gasolina93',
    source: 'CNE (Comisi\u00F3n Nacional de Energ\u00EDa)',
    sourceUrl: 'https://www.cne.cl/',
  },
  AU: {
    code: 'AU',
    name: 'Australia (NSW)',
    flag: '\u{1F1E6}\u{1F1FA}',
    center: [151.2093, -33.8688],
    zoom: 6,
    currency: 'c',
    unit: 'L',
    fuelTypes: [
      { id: 'E10', label: 'E10' },
      { id: 'U91', label: 'Unleaded 91' },
      { id: 'P95', label: 'Premium 95' },
      { id: 'P98', label: 'Premium 98' },
      { id: 'DL', label: 'Diesel' },
      { id: 'LPG', label: 'LPG' },
    ],
    defaultFuel: 'E10',
    source: 'FuelCheck NSW',
    sourceUrl: 'https://api.nsw.gov.au/',
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    flag: '\u{1F1F2}\u{1F1FD}',
    center: [-99.1332, 19.4326],
    zoom: 6,
    currency: '$',
    unit: 'L',
    fuelTypes: [
      { id: 'regular', label: 'Regular' },
      { id: 'premium', label: 'Premium' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'regular',
    source: 'CRE (datos.gob.mx)',
    sourceUrl: 'https://datos.gob.mx/',
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    flag: '\u{1F1E7}\u{1F1F7}',
    center: [-47.8825, -15.7942],
    zoom: 5,
    currency: 'R$',
    unit: 'L',
    fuelTypes: [
      { id: 'gasolina', label: 'Gasolina Comum' },
      { id: 'gasolina_ad', label: 'Gasolina Aditivada' },
      { id: 'etanol', label: 'Etanol' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'gnv', label: 'GNV' },
    ],
    defaultFuel: 'gasolina',
    source: 'ANP (Ag\u00EAncia Nacional do Petr\u00F3leo)',
    sourceUrl: 'https://www.gov.br/anp/',
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    flag: '\u{1F1E6}\u{1F1F7}',
    center: [-58.3816, -34.6037],
    zoom: 5,
    currency: '$',
    unit: 'L',
    fuelTypes: [
      { id: 'nafta_super', label: 'Nafta S\u00FAper' },
      { id: 'nafta_premium', label: 'Nafta Premium' },
      { id: 'diesel', label: 'Diesel' },
      { id: 'diesel_premium', label: 'Diesel Premium' },
      { id: 'gnc', label: 'GNC' },
    ],
    defaultFuel: 'nafta_super',
    source: 'Secretar\u00EDa de Energ\u00EDa',
    sourceUrl: 'https://datos.gob.ar/dataset/energia-precios-surtidor',
  },
  CH: {
    code: 'CH',
    name: 'Switzerland',
    flag: '\u{1F1E8}\u{1F1ED}',
    center: [8.2275, 46.8182],
    zoom: 7,
    currency: 'CHF',
    unit: 'L',
    fuelTypes: [
      { id: 'E95', label: 'Benzin 95' },
      { id: 'E98', label: 'Benzin 98' },
      { id: 'Diesel', label: 'Diesel' },
    ],
    defaultFuel: 'E95',
    source: 'Comparis.ch (TCS)',
    sourceUrl: 'https://www.comparis.ch/benzin-preise',
  },
  US: {
    code: 'US',
    name: 'United States',
    flag: '\u{1F1FA}\u{1F1F8}',
    center: [-98.5795, 39.8283],
    zoom: 4,
    currency: '$',
    unit: 'gal',
    fuelTypes: [
      { id: 'regular', label: 'Regular (87)' },
      { id: 'midgrade', label: 'Mid-Grade (89)' },
      { id: 'premium', label: 'Premium (91-93)' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'regular',
    source: 'Demo data (no public API)',
    sourceUrl: '',
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    flag: '\u{1F1E8}\u{1F1E6}',
    center: [-75.6972, 45.4215],
    zoom: 4,
    currency: 'C$',
    unit: 'L',
    fuelTypes: [
      { id: 'regular', label: 'Regular (87)' },
      { id: 'midgrade', label: 'Mid-Grade (89)' },
      { id: 'premium', label: 'Premium (91-93)' },
      { id: 'diesel', label: 'Diesel' },
    ],
    defaultFuel: 'regular',
    source: 'Demo data (no public API)',
    sourceUrl: '',
  },
};

export const DEFAULT_COUNTRY = 'FR';
