name = "fuel-saver-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

workers_dev = true

routes = [
  { pattern = "api.fuelsaver.one/*", zone_name = "fuelsaver.one" }
]

[triggers]
crons = ["0 */4 * * *"]

[[kv_namespaces]]
binding = "FUEL_KV"
id = "70110949bef446be9e58dfee01453dfd"

[vars]
BRAZIL_WORKER_URL = "https://fuel-saver-brazil.my-trendy-videos.workers.dev"
MAPBOX_TOKEN = "pk.eyJ1IjoieW9qaW1ibzQ1IiwiYSI6ImNtbXNnbXU1cjFjODMycHB6ejU0cXk3YmcifQ.Jmgmyev4QgLlgtuzvTV9sw"
FSQ_CLIENT_ID = "GFTY2OR0F2NM3XM3CETZDTZMVD32A4RYOKGPZS5YAXQOFSI2"
FSQ_CLIENT_SECRET = "KYDCRJKA4XW24B4JRTO1JAAHXF5BWTM2VO42U1YOH04LNKAX"
GOOGLE_PLACES_KEY = "AIzaSyDV5Bg3kUgwpkUbGkOMdabq_ju4uO8w36g"
BRANDFETCH_KEY = "YZ7RNm+jFb1vT90nDK+3Ro9lETa9J/xGXGEj045MoUI="
FUELO_API_KEY = "fc22ebef10f130a"
